name: Push actions

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
    - '.github/workflows/**'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: "actions/checkout@v2"

        - name: HACS Action
          uses: "hacs/action@main"
          with:
            category: "integration"
            ignore: brands wheels

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"

  style:
    runs-on: "ubuntu-latest"
    name: Check style formatting
    steps:
        - uses: "actions/checkout@v2"
        - uses: "actions/setup-python@v1"
          with:
            python-version: "3.x"
        - run: python3 -m pip install black
        - run: black .
